import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-slate-500 py-4">
      <div className="container mx-auto px-4 flex justify-between items-center">
        {/* Left-aligned Nav */}
        <nav className="flex space-x-6">
          <Link href="/" className="text-white hover:underline">
            Home
          </Link>
          <Link href="/courses" className="text-white hover:underline">
            Courses
          </Link>
          <Link href="/timeline" className="text-white hover:underline">
            Timeline
          </Link>
          <Link href="/about" className="text-white hover:underline">
            About
          </Link>
        </nav>

        {/* Right-aligned Nav */}
        <nav className="flex space-x-6">
          <Link href="/login" className="text-white hover:underline">
            Login
          </Link>
          <Link href="/signup" className="text-white hover:underline">
            Create Account
          </Link>
        </nav>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer className="w-full bg-gray-900 text-white p-5 text-center mt-10 border-t border-gray-700">
      <p className="text-gray-300 text-sm md:text-base">
        © 2025 AI Powered Language Tutor | Created by Bryan Melo
      </p>
      <div className="flex justify-center gap-4 mt-2">
        <a
          href="https://github.com/bryan-melo"
          target="_blank"
          rel="noopener noreferrer"
          className="text-gray-300 hover:text-white transition duration-200"
        >
          GitHub
        </a>
        <a>|</a>
        <a
          href="https://linkedin.com/in/bryan-melo"
          target="_blank"
          rel="noopener noreferrer"
          className="text-gray-300 hover:text-white transition duration-200"
        >
          LinkedIn
        </a>
      </div>
    </footer>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
